<?php

namespace SiteBundle\Repository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function findAllNotEmpty()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM SiteBundle:Categoria p, SiteBundle:Conteudo c'
            )
            ->getResult();
    }*/
    
    public function findAllOrderByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM SiteBundle:Categoria p INNER JOIN p.conteudos' //p.conteudos é o nome da relação definida na entidade
            )
            ->getResult();
    }
}
